function print_rode_table(table,tp)

% Prints the tables generated by rode
% 
% CALL SEQUENCE: print_rode_table(table,tp)
%
% INPUT:
%   table    tables returned by rode
%   tp       parameters returned by a call to table_param
%
% Print the tables generated by rode in a human readable manner

% PROGRAMMING by Carl Christian Kjelgaard Mikkelsen
%   2024-03-08  Initial programming and testing

m=size(table);
% One or more subtables?
dim=1;
if numel(m)==3
    dim=m(3);
end

if (dim==1)
    fprintf("Data related to component %d\n",1);
    print_table(table,tp);
else
    for i=1:dim
        fprintf("Data related to component %d\n",i);
        print_table(table(:,:,i),tp);
        fprintf('\n');
    end
end